package com.news18.init;

import org.openqa.selenium.WebDriver;

import com.news18.api.commonpages.AkamaiPlayerPage;
import com.news18.assampages.DesktopAssamArticleConsumptionPage;
import com.news18.assampages.DesktopAssamLandingPage;
import com.news18.assampages.DesktopAssamPhotogalleryConsumptionPage;
import com.news18.assampages.DesktopAssamSectionPage;
import com.news18.assampages.DesktopAssamSportsPage;
import com.news18.assampages.DesktopAssamVideosPage;
import com.news18.assampages.MobileAssamArticleConsumptionPage;
import com.news18.assampages.MobileAssamCricketNextPage;
import com.news18.assampages.MobileAssamLandingPage;
import com.news18.assampages.MobileAssamPhotogalleryConsumptionPage;
import com.news18.assampages.MobileAssamSectionPage;
import com.news18.assampages.MobileAssamVideosSectionPage;
import com.news18.bengalipages.DesktopBengaliArticleConsumptionPage;
import com.news18.bengalipages.DesktopBengaliCricketNextPage;
import com.news18.bengalipages.DesktopBengaliLandingPage;
import com.news18.bengalipages.DesktopBengaliPhotoGalleryConsumptionPage;
import com.news18.bengalipages.DesktopBengaliSectionPage;
import com.news18.bengalipages.DesktopBengaliVideosPage;
import com.news18.bengalipages.MobileBengaliArticleConsumptionPage;
import com.news18.bengalipages.MobileBengaliCricketNextPage;
import com.news18.bengalipages.MobileBengaliLandingPage;
import com.news18.bengalipages.MobileBengaliPhotogalleryConsumptionPage;
import com.news18.bengalipages.MobileBengaliSectionPage;
import com.news18.bengalipages.MobileBengaliVideoSectionPage;
import com.news18.commonpages.AMPValidatorPage;
import com.news18.commonpages.DesktopAdsValidation;
import com.news18.commonpages.DesktopOutbrainValidation;
import com.news18.commonpages.GAComscoreAMPValidation;
import com.news18.commonpages.GAComscoreValidation;
import com.news18.commonpages.HomePageLinksValidation;
import com.news18.commonpages.ImageValidationPage;
import com.news18.commonpages.IzootoValidatorPage;
import com.news18.commonpages.MetaTagContentValidation;
import com.news18.commonpages.MetaTagValidation;
import com.news18.commonpages.MobileAdsValidation;
import com.news18.commonpages.MobileOutbrainValidation;
import com.news18.commonpages.StructuredSchemaValidation;
import com.news18.commonpages.VerifyLatestNewsUpdatedTime;
import com.news18.commonpages.VerifySocialShareIcons;
import com.news18.englishpages.AMPArticleConsumptionPage;
import com.news18.englishpages.AMPCricketNextPage;
import com.news18.englishpages.AMPLandingPage;
import com.news18.englishpages.AMPPhotoArticleConsumptionPage;
import com.news18.englishpages.AMPSanityLandingPage;
import com.news18.englishpages.AMPSectionPage;
import com.news18.englishpages.DesktopArticleConsumptionPage;
import com.news18.englishpages.DesktopCricketNextPage;
import com.news18.englishpages.DesktopLandingPage;
import com.news18.englishpages.DesktopLiveblogPage;
import com.news18.englishpages.DesktopPhotoGalleryConsumptionPage;
import com.news18.englishpages.DesktopSanityLandingPage;
import com.news18.englishpages.MobileArticleConsumptionPage;
import com.news18.englishpages.MobileCricketNextPage;
import com.news18.englishpages.MobileLandingPage;
import com.news18.englishpages.MobileLiveblogPage;
import com.news18.englishpages.MobilePhotoGalleryConsumptionPage;
import com.news18.englishpages.MobileSanityLandingPage;
import com.news18.englishpages.MobileSectionPage;
import com.news18.englishpages.MobileVideosArticlePage;
import com.news18.gujaratipages.DesktopGujaratiArticleConsumptionPage;
import com.news18.gujaratipages.DesktopGujaratiLandingPage;
import com.news18.gujaratipages.DesktopGujaratiLiveBlogPage;
import com.news18.gujaratipages.DesktopGujaratiPhotogalleryConsumptionPage;
import com.news18.gujaratipages.DesktopGujaratiSanityLandingPage;
import com.news18.gujaratipages.DesktopGujaratiSectionPage;
import com.news18.gujaratipages.DesktopGujaratiSportsPage;
import com.news18.gujaratipages.DesktopGujaratiVideosPage;
import com.news18.gujaratipages.MobileGujaratiArticleConsumptionPage;
import com.news18.gujaratipages.MobileGujaratiLandingPage;
import com.news18.gujaratipages.MobileGujaratiPhotogalleryConsumptionPage;
import com.news18.gujaratipages.MobileGujaratiSanityLandingPage;
import com.news18.gujaratipages.MobileGujaratiSectionPage;
import com.news18.gujaratipages.MobileGujaratiSportsPage;
import com.news18.gujaratipages.MobileGujaratiVideosPage;
import com.news18.hindipages.AMPHindiLandingPage;
import com.news18.hindipages.AMPHindiSanityLandingPage;
import com.news18.hindipages.DesktopHindiArticleConsumptionPage;
import com.news18.hindipages.DesktopHindiCricketNextPage;
import com.news18.hindipages.DesktopHindiLandingPage;
import com.news18.hindipages.DesktopHindiLiveBlogPage;
import com.news18.hindipages.DesktopHindiPhotoGalleryConsumptionPage;
import com.news18.hindipages.DesktopHindiSanityLandingPage;
import com.news18.hindipages.DesktopHindiSectionPage;
import com.news18.hindipages.DesktopHindiVideosPage;
import com.news18.hindipages.MobileHindiArticleConsumptionPage;
import com.news18.hindipages.MobileHindiCricketNextPage;
import com.news18.hindipages.MobileHindiLandingPage;
import com.news18.hindipages.MobileHindiPhotoGalleryConsumptionPage;
import com.news18.hindipages.MobileHindiSanityLandingPage;
import com.news18.hindipages.MobileHindiSectionPage;
import com.news18.hindipages.MobileHindiVideoSectionPage;
import com.news18.kannadapages.DesktopKannadaArticleConsumptionPage;
import com.news18.kannadapages.DesktopKannadaLandingPage;
import com.news18.kannadapages.DesktopKannadaPhotogalleryConsumptionPage;
import com.news18.kannadapages.DesktopKannadaSectionPage;
import com.news18.kannadapages.DesktopKannadaSportsPage;
import com.news18.kannadapages.DesktopKannadaVideosPage;
import com.news18.kannadapages.MobileKannadaArticleConsumptionPage;
import com.news18.kannadapages.MobileKannadaLandingPage;
import com.news18.kannadapages.MobileKannadaPhotogalleryConsumptionPage;
import com.news18.kannadapages.MobileKannadaSectionPage;
import com.news18.kannadapages.MobileKannadaSportsPage;
import com.news18.kannadapages.MobileKannadaVideoPage;
import com.news18.lokmatpages.DesktopLokmatArticleConsumptionPage;
import com.news18.lokmatpages.DesktopLokmatLandingPage;
import com.news18.lokmatpages.DesktopLokmatPhotogalleryConsumptionPage;
import com.news18.lokmatpages.DesktopLokmatSectionPage;
import com.news18.lokmatpages.DesktopLokmatSportsPage;
import com.news18.lokmatpages.DesktopLokmatVideosPage;
import com.news18.lokmatpages.MobileLokmatArticleConsumptionPage;
import com.news18.lokmatpages.MobileLokmatLandingPage;
import com.news18.lokmatpages.MobileLokmatPhotogalleryConsumptionPage;
import com.news18.lokmatpages.MobileLokmatSectionPage;
import com.news18.lokmatpages.MobileLokmatSportsPage;
import com.news18.lokmatpages.MobileLokmatVideoPage;
import com.news18.malayalampages.DesktopMalayalamArticleConsumptionPage;
import com.news18.malayalampages.DesktopMalayalamLandingPage;
import com.news18.malayalampages.DesktopMalayalamSectionPage;
import com.news18.malayalampages.DesktopMalayalamSportsPage;
import com.news18.malayalampages.DesktopMalayalamVideosPage;
import com.news18.malayalampages.DesktopMalyalamPhotogalleryConsumptionPage;
import com.news18.malayalampages.MobileMalayalamArticleConsumptionPage;
import com.news18.malayalampages.MobileMalayalamLandingPage;
import com.news18.malayalampages.MobileMalayalamPhotogalleryConsumptionPage;
import com.news18.malayalampages.MobileMalayalamSectionPage;
import com.news18.malayalampages.MobileMalayalamSportsPage;
import com.news18.malayalampages.MobileMalayalamVideosPage;
import com.news18.odiapages.DesktopOdiaArticleConsumptionPage;
import com.news18.odiapages.DesktopOdiaLandingPage;
import com.news18.odiapages.DesktopOdiaPhotogalleryConsumptionPage;
import com.news18.odiapages.DesktopOdiaSectionPage;
import com.news18.odiapages.DesktopOdiaSportsPage;
import com.news18.odiapages.DesktopOdiaVideosPage;
import com.news18.odiapages.MobileOdiaArticleConsumptionPage;
import com.news18.odiapages.MobileOdiaCricketNextPage;
import com.news18.odiapages.MobileOdiaLandingPage;
import com.news18.odiapages.MobileOdiaPhotogalleryConsumptionPage;
import com.news18.odiapages.MobileOdiaSectionPage;
import com.news18.odiapages.MobileOdiaVideoSectionPage;
import com.news18.punjabipages.DesktopPunjabArticleConsumptionPage;
import com.news18.punjabipages.DesktopPunjabLandingPage;
import com.news18.punjabipages.DesktopPunjabPhotogalleryConsumptionPage;
import com.news18.punjabipages.DesktopPunjabSectionPage;
import com.news18.punjabipages.DesktopPunjabSportsPage;
import com.news18.punjabipages.DesktopPunjabVideosPage;
import com.news18.punjabipages.MobilePunjabArticleConsumptionPage;
import com.news18.punjabipages.MobilePunjabCricketNextPage;
import com.news18.punjabipages.MobilePunjabLandingPage;
import com.news18.punjabipages.MobilePunjabPhotogalleryConsumptionPage;
import com.news18.punjabipages.MobilePunjabSectionPage;
import com.news18.punjabipages.MobilePunjabVideoSectionPage;
import com.news18.tamilpages.DesktopTamilArticleConsumptionPage;
import com.news18.tamilpages.DesktopTamilLandingPage;
import com.news18.tamilpages.DesktopTamilPhotogalleryConsumptionPage;
import com.news18.tamilpages.DesktopTamilSectionPage;
import com.news18.tamilpages.DesktopTamilSportsPage;
import com.news18.tamilpages.DesktopTamilVideosPage;
import com.news18.tamilpages.MobileTamilArticleConsumptionPage;
import com.news18.tamilpages.MobileTamilCricketNextPage;
import com.news18.tamilpages.MobileTamilLandingPage;
import com.news18.tamilpages.MobileTamilPhotogalleryConsumptionPage;
import com.news18.tamilpages.MobileTamilSectionPage;
import com.news18.tamilpages.MobileTamilVideoSectionPage;
import com.news18.telugupages.DesktopTeluguArticleConsumptionPage;
import com.news18.telugupages.DesktopTeluguLandingPage;
import com.news18.telugupages.DesktopTeluguPhotogalleryConsumptionPage;
import com.news18.telugupages.DesktopTeluguSectionPage;
import com.news18.telugupages.DesktopTeluguSportsPage;
import com.news18.telugupages.DesktopTeluguVideosPage;
import com.news18.telugupages.MobileTeluguArticleConsumptionPage;
import com.news18.telugupages.MobileTeluguCricketNextPage;
import com.news18.telugupages.MobileTeluguLandingPage;
import com.news18.telugupages.MobileTeluguPhotogalleryConsumptionPage;
import com.news18.telugupages.MobileTeluguSectionPage;
import com.news18.telugupages.MobileTeluguVideoSectionPage;
import com.news18.urdupages.DesktopUrduArticleConsumptionPage;
import com.news18.urdupages.DesktopUrduLandingPage;
import com.news18.urdupages.DesktopUrduPhotogalleryConsumptionPage;
import com.news18.urdupages.DesktopUrduSectionPage;
import com.news18.urdupages.DesktopUrduSportsPage;
import com.news18.urdupages.DesktopUrduVideosPage;
import com.news18.urdupages.MobileUrduArticleConsumptionPage;
import com.news18.urdupages.MobileUrduLandingPage;
import com.news18.urdupages.MobileUrduPhotogalleryConsumptionPage;
import com.news18.urdupages.MobileUrduSectionPage;
import com.news18.urdupages.MobileUrduSportsPage;
import com.news18.urdupages.MobileUrduVideoPage;

/**
 * @author Danish R
 * This class contains InitializePages for POM Pages
 */
public class InitializePages {

	public MetaTagContentValidation metaTagContentValidation;
	public DesktopAdsValidation desktopAdsValidation;
	public MobileAdsValidation mobileAdsValidation;
	public DesktopLandingPage desktopLandingPage;
	public AMPCricketNextPage ampCricketNextPage;
	public DesktopPhotoGalleryConsumptionPage desktopphotoGalleryConsumptionPage;
	public DesktopHindiLandingPage desktopHindiLandingPage;
	public DesktopHindiPhotoGalleryConsumptionPage desktopHindiPhotoGalleryConsumptionPage;
	public DesktopBengaliLandingPage desktopBengaliLandingPage;
	public DesktopBengaliPhotoGalleryConsumptionPage desktopBengaliPhotoGalleryConsumptionPage;
	public DesktopLokmatLandingPage desktopLokmatLandingPage;
	public DesktopLokmatPhotogalleryConsumptionPage desktopLokmatPhotogalleryConsumptionPage;
	public DesktopGujaratiLandingPage desktopGujaratiLandingPage;
	public DesktopGujaratiPhotogalleryConsumptionPage desktopGujaratiPhotogalleryConsumptionPage;
	public DesktopKannadaLandingPage desktopKannadaLandingPage;
	public DesktopKannadaPhotogalleryConsumptionPage  desktopKannadaPhotogalleryConsumptionPage;
	public DesktopMalayalamLandingPage desktopMalayalamLandingPage;
	public DesktopMalyalamPhotogalleryConsumptionPage desktopMalayalamPhotogalleryConsumptionPage;
	public DesktopOdiaLandingPage desktopOdiaLandingPage;
	public DesktopOdiaPhotogalleryConsumptionPage desktopOdiaPhotogalleryConsumptionPage;
	public DesktopPunjabLandingPage desktopPunjabLandingPage;
	public DesktopPunjabPhotogalleryConsumptionPage desktopPunjabPhotogalleryConsumptionPage;
	public DesktopTamilLandingPage desktopTamilLandingPage;
	public DesktopTamilPhotogalleryConsumptionPage desktopTamilPhotogalleryConsumptionPage;
	public DesktopTeluguLandingPage desktopTeluguLandingPage;
	public DesktopTeluguPhotogalleryConsumptionPage desktopTeluguPhotogalleryConsumptionPage;
	public DesktopUrduLandingPage desktopUrduLandingPage;
	public DesktopUrduPhotogalleryConsumptionPage desktopUrduPhotogalleryConsumptionPage;
	public DesktopAssamLandingPage desktopAssamLandingPage;
	public DesktopAssamPhotogalleryConsumptionPage desktopAssamPhotogalleryConsumptionPage;
	public MobileHindiLandingPage mobileHindiLandingPage;
	public MobileBengaliLandingPage mobileBengaliLandingPage;
	public MobileLandingPage mobileLandingPage;
	public MobileLokmatLandingPage mobileLokmatLandingPage;
	public MobileKannadaLandingPage mobileKannadaLandingPage;
	public MobileMalayalamLandingPage mobileMalayalamLandingPage;
	public MobileTamilLandingPage mobileTamilLandingPage;
	public DesktopArticleConsumptionPage desktopArticleConsumptionPage;
	public MobileArticleConsumptionPage mobileArticleConsumptionPage;
	public MobilePhotoGalleryConsumptionPage mobilePhotoGalleryConsumptionPage;
	public MobileAssamLandingPage mobileAssamLandingPage;
	public MobilePunjabLandingPage mobilePunjabLandingPage;
	public MobileTeluguLandingPage mobileTeluguLandingPage;
	public MobileUrduLandingPage urduMobileLandingPage;
	public MobileGujaratiLandingPage mobileGujaratiLandingPage;
	public MobileOdiaLandingPage mobileOdiaLandingPage;
	public AMPSectionPage ampSectionPage;
	public DesktopHindiCricketNextPage desktopHindiCricketNextPage;
	public DesktopHindiVideosPage desktopHindiVideosPage;
	public DesktopHindiSectionPage desktopHindiSectionPage;
	public DesktopKannadaSportsPage desktopKannadaSportsPage;
	public DesktopKannadaVideosPage desktopKannadaVideosPage;
	public DesktopKannadaSectionPage desktopKannadaSectionPage;
	public DesktopLokmatSportsPage desktopLokmatSportsPage;
	public DesktopLokmatSectionPage desktopLokmatSectionPage;
	public DesktopLokmatVideosPage desktopLokmatVideosPage;
	public DesktopMalayalamSportsPage desktopMalayalamSportsPage;
	public DesktopMalayalamSectionPage desktopMalayalamSectionPage;
	public DesktopMalayalamVideosPage desktopMalayalamVideosPage;
	public DesktopOdiaSportsPage desktopOdiaSportsPage;
	public DesktopOdiaSectionPage desktopOdiaSectionPage;
	public DesktopOdiaVideosPage desktopOdiaVideosPage;
	public DesktopPunjabSportsPage desktopPunjabSportsPage;
	public DesktopPunjabSectionPage desktopPunjabSectionPage;
	public DesktopPunjabVideosPage desktopPunjabVideosPage;
	public DesktopTamilSportsPage desktopTamilSportsPage;
	public DesktopTamilSectionPage desktopTamilSectionPage;
	public DesktopTamilVideosPage desktopTamilVideosPage;
	public DesktopTeluguSportsPage desktopTeluguSportsPage;
	public DesktopTeluguSectionPage desktopTeluguSectionPage;
	public DesktopTeluguVideosPage desktopTeluguVideosPage;
	public DesktopUrduSportsPage desktopUrduSportsPage;
	public DesktopUrduSectionPage desktopUrduSectionPage;
	public DesktopUrduVideosPage desktopUrduVideosPage;
	public DesktopAssamSportsPage desktopAssamSportsPage;
	public DesktopAssamSectionPage desktopAssamSectionPage;
	public DesktopAssamVideosPage desktopAssamVideosPage;
	public DesktopBengaliCricketNextPage desktopBengaliCricketNextPage;
	public DesktopBengaliSectionPage desktopBengaliSectionPage;
	public DesktopBengaliVideosPage desktopBengaliVideosPage;
	public DesktopGujaratiSportsPage desktopGujaratiSportsPage;
	public DesktopGujaratiSectionPage desktopGujaratiSectionPage;
	public DesktopGujaratiVideosPage desktopGujaratiVideosPage;
	public DesktopHindiArticleConsumptionPage desktopHindiArticleConsumptionPage;
	public DesktopBengaliArticleConsumptionPage desktopBengaliArticleConsumptionPage;
	public DesktopLokmatArticleConsumptionPage desktopLokmatArticleConsumptionPage;
	public DesktopGujaratiArticleConsumptionPage desktopGujaratiArticleConsumptionPage;
	public DesktopKannadaArticleConsumptionPage desktopKannadaArticleConsumptionPage;
	public DesktopTamilArticleConsumptionPage desktopTamilArticleConsumptionPage;
	public DesktopMalayalamArticleConsumptionPage desktopMalayalamArticleConsumptionPage;
	public DesktopTeluguArticleConsumptionPage desktopTeluguArticleConsumptionPage;
	public DesktopPunjabArticleConsumptionPage desktopPunjabArticleConsumptionPage;
	public DesktopUrduArticleConsumptionPage desktopUrduArticleConsumptionPage;
	public DesktopAssamArticleConsumptionPage desktopAssamArticleConsumptionPage;
	public DesktopOdiaArticleConsumptionPage desktopOdiaArticleConsumptionPage;
	public MobileHindiArticleConsumptionPage mobileHindiArticleConsumptionPage;
	public MobileBengaliArticleConsumptionPage mobileBengaliArticleConsumptionPage;
	public MobileLokmatArticleConsumptionPage mobileLokmatArticleConsumptionPage;
	public MobileGujaratiArticleConsumptionPage mobileGujaratiArticleConsumptionPage;
	public MobileKannadaArticleConsumptionPage mobileKannadaArticleConsumptionPage;
	public MobileAssamPhotogalleryConsumptionPage mobileAssamPhotogalleryConsumptionPage;
	public MobileBengaliPhotogalleryConsumptionPage mobileBengaliPhotogalleryConsumptionPage;
	public MobileGujaratiPhotogalleryConsumptionPage mobileGujaratiPhotogalleryConsumptionPage;
	public MobileHindiPhotoGalleryConsumptionPage mobileHindiPhotoGalleryConsumptionPage;
	public MobileKannadaPhotogalleryConsumptionPage mobileKannadaPhotogalleryConsumptionPage;
	public MobileLokmatPhotogalleryConsumptionPage mobileLokmatPhotogalleryConsumptionPage;
	public MobileMalayalamPhotogalleryConsumptionPage mobileMalayalamPhotogalleryConsumptionPage;
	public MobileOdiaPhotogalleryConsumptionPage mobileOdiaPhotogalleryConsumptionPage;
	public MobilePunjabPhotogalleryConsumptionPage mobilePunjabPhotogalleryConsumptionPage;
	public MobileTamilPhotogalleryConsumptionPage mobileTamilPhotogalleryConsumptionPage;
	public MobileTeluguPhotogalleryConsumptionPage mobileTeluguPhotogalleryConsumptionPage;
	public MobileUrduPhotogalleryConsumptionPage mobileUrduPhotogalleryConsumptionPage;
	public MobileTamilArticleConsumptionPage mobileTamilArticleConsumptionPage;
	public MobileMalayalamArticleConsumptionPage mobileMalayalamArticleConsumptionPage;
	public MobileTeluguArticleConsumptionPage mobileTeluguArticleConsumptionPage;
	public MobilePunjabArticleConsumptionPage mobilePunjabArticleConsumptionPage;
	public MobileUrduArticleConsumptionPage mobileUrduArticleConsumptionPage;
	public MobileOdiaArticleConsumptionPage mobileOdiaArticleConsumptionPage;
	public MobileAssamArticleConsumptionPage mobileAssamArticleConsumptionPage;
	public DesktopLiveblogPage desktopLiveblogPage;
	public DesktopHindiLiveBlogPage desktopHindiLiveBlogPage;
	public MobileGujaratiVideosPage mobileGujaratiVideosPage;
	public MobileKannadaVideoPage mobileKannadaVideoPage;
	public MobileMalayalamVideosPage mobileMalayalamVideosPage;
	public MobileUrduVideoPage mobileUrduVideoPage;
	public DesktopCricketNextPage desktopCricketNextPage;
	public MobileLokmatVideoPage  mobileLokmatVideoPage;
	public MobileVideosArticlePage mobileVideosArticlePage;
	public DesktopGujaratiLiveBlogPage desktopGujaratiLiveBlogPage;
	public MobileLiveblogPage mobileLiveblogPage;
	public MobileCricketNextPage mobileCricketNextPage;
	public MobileSectionPage mobileSectionPage;
	public MobileGujaratiSportsPage mobileGujaratiSportsPage;
	public MobileGujaratiSectionPage mobileGujaratiSectionPage;
	public AMPArticleConsumptionPage ampArticleConsumptionPage;
	public MobileAssamSectionPage mobileAssamSectionPage; 
	public MobileAssamCricketNextPage mobileAssamCricketNextPage;
	public MobileAssamVideosSectionPage mobileAssamVideosSectionPage;
	public MobileBengaliSectionPage mobileBengaliSectionPage; 
	public MobileBengaliCricketNextPage mobileBengaliCricketNextPage;
	public MobileBengaliVideoSectionPage mobileBengaliVideoSectionPage;
	public MobileOdiaSectionPage mobileOdiaSectionPage; 
	public MobileOdiaCricketNextPage mobileOdiaCricketNextPage;
	public MobileOdiaVideoSectionPage mobileOdiaVideoSectionPage;
	public MobileMalayalamSectionPage mobileMalayalamSectionPage;
	public MobileMalayalamSportsPage mobileMalayalamSportsPage;
	public MobileUrduSectionPage mobileUrduSectionPage;
	public MobileUrduSportsPage mobileUrduSportsPage;
	public MobileKannadaSectionPage mobileKannadaSectionPage;
	public MobileKannadaSportsPage mobileKannadaSportsPage;
	public MobileLokmatSectionPage mobileLokmatSectionPage;
	public MobileLokmatSportsPage mobileLokmatSportsPage;
	public MobileHindiCricketNextPage mobileHindiCricketNextPage;
	public MobileHindiSectionPage mobileHindiSectionPage;
	public MobileHindiVideoSectionPage mobileHindiVideoSectionPage;
	public MobilePunjabSectionPage mobilePunjabSectionPage;
	public MobilePunjabCricketNextPage mobilePunjabCricketNextPage;
	public MobilePunjabVideoSectionPage mobilePunjabVideoSectionPage;
	public MobileTeluguSectionPage mobileTeluguSectionPage; 
	public MobileTeluguCricketNextPage mobileTeluguCricketNextPage;
	public MobileTeluguVideoSectionPage mobileTeluguVideoSectionPage;
	public MobileTamilSectionPage mobileTamilSectionPage; 
	public MobileTamilCricketNextPage mobileTamilCricketNextPage;
	public MobileTamilVideoSectionPage mobileTamilVideoSectionPage;
	public MobileAssamVideosSectionPage mobileAssamVideoSectionPage;
	public AMPValidatorPage ampValidatorPage;
	public HomePageLinksValidation homePageLinksValidation;
	public MetaTagValidation desktopMetaTagValidation;
	public GAComscoreValidation gaComscoreValidation;
	public DesktopOutbrainValidation desktopOutbrainValidation;
	public MobileOutbrainValidation mobileOutbrainValidation;
	public StructuredSchemaValidation structuredSchemaValidation;
	public VerifySocialShareIcons verifySocialShareIcons;
	public VerifyLatestNewsUpdatedTime verifyLatestNewsUpdatedTime;
	public IzootoValidatorPage izootoValidatorPage;
	public ImageValidationPage imageValidationPage;
	public AMPPhotoArticleConsumptionPage ampPhotoArticleConsumptionPage;
	public GAComscoreAMPValidation gaComscoreAMPValidation;
	public AkamaiPlayerPage akamaipage;
	public AMPLandingPage ampLandingPage;
	public AMPHindiLandingPage ampHindiLandingPage;
	public DesktopSanityLandingPage desktopSanityLandingPage;
	public MobileSanityLandingPage mobileSanityLandingPage;
	public AMPSanityLandingPage ampSanityLandingPage;
	public DesktopHindiSanityLandingPage desktopHindiSanityLandingPage;
	public MobileHindiSanityLandingPage mobileHindiSanityLandingPage;
	public AMPHindiSanityLandingPage ampHindiSanityLandingPage;
	public DesktopGujaratiSanityLandingPage desktopGujaratiSanityLandingPage;
	public MobileGujaratiSanityLandingPage mobileGujaratiSanityLandingPage;
	
	
	
	InitializePages(WebDriver driver) {
		mobileGujaratiSanityLandingPage=new MobileGujaratiSanityLandingPage(driver);
		desktopGujaratiSanityLandingPage=new DesktopGujaratiSanityLandingPage(driver);
		ampLandingPage=new AMPLandingPage(driver);
		akamaipage=new AkamaiPlayerPage(driver);
		metaTagContentValidation =new MetaTagContentValidation(driver);
		imageValidationPage = new ImageValidationPage(driver);
		izootoValidatorPage = new IzootoValidatorPage(driver);
		desktopAdsValidation = new DesktopAdsValidation(driver);
		mobileAdsValidation = new MobileAdsValidation(driver);
		desktopTamilLandingPage = new DesktopTamilLandingPage(driver);
		mobileTamilLandingPage = new MobileTamilLandingPage(driver);
		mobileMalayalamLandingPage = new MobileMalayalamLandingPage(driver);
		mobileKannadaLandingPage = new MobileKannadaLandingPage(driver);
		mobileLandingPage = new MobileLandingPage(driver);
		mobileBengaliLandingPage = new MobileBengaliLandingPage(driver);
		mobileHindiLandingPage = new MobileHindiLandingPage(driver);
		desktopAssamPhotogalleryConsumptionPage = new DesktopAssamPhotogalleryConsumptionPage(driver);
		desktopAssamLandingPage = new DesktopAssamLandingPage(driver);
		desktopUrduPhotogalleryConsumptionPage = new DesktopUrduPhotogalleryConsumptionPage(driver);
		desktopUrduLandingPage = new DesktopUrduLandingPage(driver);
		desktopTeluguPhotogalleryConsumptionPage = new DesktopTeluguPhotogalleryConsumptionPage(driver);
		desktopTeluguLandingPage = new DesktopTeluguLandingPage(driver);
		desktopTamilPhotogalleryConsumptionPage = new DesktopTamilPhotogalleryConsumptionPage(driver);
		desktopPunjabPhotogalleryConsumptionPage = new DesktopPunjabPhotogalleryConsumptionPage(driver);
		desktopLandingPage = new DesktopLandingPage(driver);
		ampCricketNextPage = new AMPCricketNextPage(driver);
		desktopphotoGalleryConsumptionPage = new DesktopPhotoGalleryConsumptionPage(driver);
		desktopHindiLandingPage = new DesktopHindiLandingPage(driver);
		desktopHindiPhotoGalleryConsumptionPage = new DesktopHindiPhotoGalleryConsumptionPage(driver);
		desktopBengaliLandingPage= new DesktopBengaliLandingPage(driver);
		desktopBengaliPhotoGalleryConsumptionPage= new DesktopBengaliPhotoGalleryConsumptionPage(driver);
		desktopLokmatLandingPage= new DesktopLokmatLandingPage(driver);
		desktopLokmatPhotogalleryConsumptionPage= new DesktopLokmatPhotogalleryConsumptionPage(driver);
		desktopGujaratiLandingPage = new DesktopGujaratiLandingPage(driver);
		desktopGujaratiPhotogalleryConsumptionPage = new DesktopGujaratiPhotogalleryConsumptionPage(driver);
		desktopKannadaLandingPage = new DesktopKannadaLandingPage(driver);
		desktopKannadaPhotogalleryConsumptionPage = new DesktopKannadaPhotogalleryConsumptionPage(driver);
		desktopMalayalamLandingPage = new DesktopMalayalamLandingPage(driver);
		desktopMalayalamPhotogalleryConsumptionPage = new DesktopMalyalamPhotogalleryConsumptionPage(driver);
		desktopOdiaLandingPage = new DesktopOdiaLandingPage(driver);
		desktopOdiaPhotogalleryConsumptionPage = new DesktopOdiaPhotogalleryConsumptionPage(driver);
		desktopPunjabLandingPage = new DesktopPunjabLandingPage(driver);
		desktopArticleConsumptionPage = new DesktopArticleConsumptionPage(driver);
		mobileArticleConsumptionPage = new MobileArticleConsumptionPage(driver);
		mobilePhotoGalleryConsumptionPage = new MobilePhotoGalleryConsumptionPage(driver);
		mobileLokmatLandingPage = new MobileLokmatLandingPage(driver);
		mobileAssamLandingPage=new MobileAssamLandingPage(driver);
		mobilePunjabLandingPage=new MobilePunjabLandingPage(driver);
		mobileTeluguLandingPage=new MobileTeluguLandingPage(driver);
		urduMobileLandingPage=new MobileUrduLandingPage(driver);
		mobileGujaratiLandingPage=new MobileGujaratiLandingPage(driver);
		mobileOdiaLandingPage=new MobileOdiaLandingPage(driver);
		ampSectionPage = new AMPSectionPage(driver);
		ampCricketNextPage = new AMPCricketNextPage(driver);
		ampSectionPage = new AMPSectionPage(driver);
		desktopHindiVideosPage = new DesktopHindiVideosPage(driver);
		desktopHindiSectionPage = new DesktopHindiSectionPage(driver);
		desktopKannadaSportsPage=new DesktopKannadaSportsPage(driver);
		desktopKannadaVideosPage=new DesktopKannadaVideosPage(driver);
		desktopKannadaSectionPage=new DesktopKannadaSectionPage(driver);
		desktopLokmatSportsPage=new DesktopLokmatSportsPage(driver);
		desktopLokmatSectionPage=new DesktopLokmatSectionPage(driver);
		desktopLokmatVideosPage=new DesktopLokmatVideosPage(driver);
		desktopMalayalamSportsPage=new DesktopMalayalamSportsPage(driver);
		desktopMalayalamSectionPage=new DesktopMalayalamSectionPage(driver);
		desktopMalayalamVideosPage= new DesktopMalayalamVideosPage(driver);
		desktopOdiaSportsPage= new DesktopOdiaSportsPage(driver);
		desktopOdiaSectionPage= new DesktopOdiaSectionPage(driver);
		desktopOdiaVideosPage= new DesktopOdiaVideosPage(driver);
		desktopPunjabSportsPage= new DesktopPunjabSportsPage(driver);
		desktopPunjabSectionPage= new DesktopPunjabSectionPage(driver);
		desktopPunjabVideosPage= new DesktopPunjabVideosPage(driver);
		desktopTamilSportsPage=new DesktopTamilSportsPage(driver);
		desktopTamilSectionPage=new DesktopTamilSectionPage(driver);
		desktopTamilVideosPage=new DesktopTamilVideosPage(driver);
		desktopTeluguSportsPage= new DesktopTeluguSportsPage(driver);
		desktopTeluguSectionPage= new DesktopTeluguSectionPage(driver);
		desktopTeluguVideosPage= new DesktopTeluguVideosPage(driver);
		desktopUrduSportsPage= new DesktopUrduSportsPage(driver);
		desktopUrduSectionPage= new DesktopUrduSectionPage(driver);
		desktopUrduVideosPage= new DesktopUrduVideosPage(driver);
		desktopAssamSportsPage= new DesktopAssamSportsPage(driver);
		desktopAssamSectionPage= new DesktopAssamSectionPage(driver);
		desktopAssamVideosPage= new DesktopAssamVideosPage(driver);
		desktopBengaliCricketNextPage=new DesktopBengaliCricketNextPage(driver);
		desktopBengaliSectionPage= new DesktopBengaliSectionPage(driver);
		desktopBengaliVideosPage=new DesktopBengaliVideosPage(driver);
		desktopGujaratiSportsPage=new DesktopGujaratiSportsPage(driver);
		desktopGujaratiSectionPage=new DesktopGujaratiSectionPage(driver);
		desktopGujaratiVideosPage=new DesktopGujaratiVideosPage(driver);
		desktopHindiArticleConsumptionPage=new DesktopHindiArticleConsumptionPage(driver);
		desktopBengaliArticleConsumptionPage=new DesktopBengaliArticleConsumptionPage(driver);
		desktopLokmatArticleConsumptionPage=new DesktopLokmatArticleConsumptionPage(driver);
		desktopGujaratiArticleConsumptionPage=new DesktopGujaratiArticleConsumptionPage(driver);
		desktopKannadaArticleConsumptionPage=new DesktopKannadaArticleConsumptionPage(driver);
		desktopTamilArticleConsumptionPage=new DesktopTamilArticleConsumptionPage(driver);
		desktopMalayalamArticleConsumptionPage=new DesktopMalayalamArticleConsumptionPage(driver);
		desktopTeluguArticleConsumptionPage=new DesktopTeluguArticleConsumptionPage(driver);
		desktopPunjabArticleConsumptionPage= new DesktopPunjabArticleConsumptionPage(driver);
		desktopUrduArticleConsumptionPage=new DesktopUrduArticleConsumptionPage(driver);
		desktopAssamArticleConsumptionPage=new DesktopAssamArticleConsumptionPage(driver);
		mobileUrduArticleConsumptionPage=new MobileUrduArticleConsumptionPage(driver);
		desktopOdiaArticleConsumptionPage=new DesktopOdiaArticleConsumptionPage(driver);
		mobileHindiArticleConsumptionPage=new MobileHindiArticleConsumptionPage(driver);
		mobileBengaliArticleConsumptionPage=new MobileBengaliArticleConsumptionPage(driver);
		mobileLokmatArticleConsumptionPage=new MobileLokmatArticleConsumptionPage(driver);
		mobileGujaratiArticleConsumptionPage=new MobileGujaratiArticleConsumptionPage(driver);
		mobileKannadaArticleConsumptionPage=new MobileKannadaArticleConsumptionPage(driver);
		mobileAssamPhotogalleryConsumptionPage=new MobileAssamPhotogalleryConsumptionPage(driver);
		mobileBengaliPhotogalleryConsumptionPage=new MobileBengaliPhotogalleryConsumptionPage(driver);
		mobileGujaratiPhotogalleryConsumptionPage=new MobileGujaratiPhotogalleryConsumptionPage(driver);
		mobileHindiPhotoGalleryConsumptionPage=new MobileHindiPhotoGalleryConsumptionPage(driver);
		mobileKannadaPhotogalleryConsumptionPage=new MobileKannadaPhotogalleryConsumptionPage(driver);
		mobileLokmatPhotogalleryConsumptionPage=new MobileLokmatPhotogalleryConsumptionPage(driver);
		mobileMalayalamPhotogalleryConsumptionPage=new MobileMalayalamPhotogalleryConsumptionPage(driver);
		mobileOdiaPhotogalleryConsumptionPage=new MobileOdiaPhotogalleryConsumptionPage(driver);
		mobilePunjabPhotogalleryConsumptionPage=new MobilePunjabPhotogalleryConsumptionPage(driver);
		mobileTamilPhotogalleryConsumptionPage=new MobileTamilPhotogalleryConsumptionPage(driver);
		mobileTeluguPhotogalleryConsumptionPage=new MobileTeluguPhotogalleryConsumptionPage(driver);
		mobileUrduPhotogalleryConsumptionPage=new MobileUrduPhotogalleryConsumptionPage(driver);
		mobileTamilArticleConsumptionPage=new MobileTamilArticleConsumptionPage(driver);
		mobileMalayalamArticleConsumptionPage=new MobileMalayalamArticleConsumptionPage(driver);
		mobileTeluguArticleConsumptionPage=new MobileTeluguArticleConsumptionPage(driver);
		mobilePunjabArticleConsumptionPage=new MobilePunjabArticleConsumptionPage(driver);
		mobileOdiaArticleConsumptionPage=new MobileOdiaArticleConsumptionPage(driver);
		mobileAssamArticleConsumptionPage=new MobileAssamArticleConsumptionPage(driver);
		desktopLiveblogPage=new DesktopLiveblogPage(driver);
		desktopHindiLiveBlogPage=new DesktopHindiLiveBlogPage(driver);
		desktopHindiCricketNextPage=new DesktopHindiCricketNextPage(driver);
		mobileGujaratiVideosPage= new MobileGujaratiVideosPage(driver);
		mobileKannadaVideoPage= new MobileKannadaVideoPage(driver);
		mobileMalayalamVideosPage=new MobileMalayalamVideosPage(driver);
		mobileUrduVideoPage= new MobileUrduVideoPage(driver);
		desktopCricketNextPage = new DesktopCricketNextPage(driver);
		mobileLokmatVideoPage = new MobileLokmatVideoPage(driver);
		mobileVideosArticlePage = new  MobileVideosArticlePage(driver);
		desktopGujaratiLiveBlogPage=new DesktopGujaratiLiveBlogPage(driver);
		mobileLiveblogPage=new MobileLiveblogPage(driver);
		mobileCricketNextPage = new MobileCricketNextPage(driver);
		mobileSectionPage = new MobileSectionPage(driver);
		mobileGujaratiSportsPage = new MobileGujaratiSportsPage(driver);
		mobileGujaratiSectionPage = new MobileGujaratiSectionPage(driver);
		ampArticleConsumptionPage= new AMPArticleConsumptionPage(driver);
		mobileAssamSectionPage =new MobileAssamSectionPage(driver);
		mobileAssamCricketNextPage=new MobileAssamCricketNextPage(driver);
		mobileAssamVideosSectionPage=new MobileAssamVideosSectionPage(driver);
		mobileBengaliSectionPage =new MobileBengaliSectionPage(driver);
		mobileBengaliCricketNextPage=new MobileBengaliCricketNextPage(driver);
		mobileBengaliVideoSectionPage=new MobileBengaliVideoSectionPage(driver);
		mobileOdiaCricketNextPage=new MobileOdiaCricketNextPage(driver);
		mobileOdiaVideoSectionPage=new MobileOdiaVideoSectionPage(driver);
		mobileMalayalamSportsPage = new MobileMalayalamSportsPage(driver);
		mobileMalayalamSectionPage = new MobileMalayalamSectionPage(driver);
		mobileUrduSectionPage = new MobileUrduSectionPage(driver);
		mobileUrduSportsPage = new MobileUrduSportsPage(driver);
		mobileKannadaSectionPage = new MobileKannadaSectionPage(driver);
		mobileKannadaSportsPage = new MobileKannadaSportsPage(driver);
		mobileLokmatSectionPage = new MobileLokmatSectionPage(driver);
		mobileLokmatSportsPage = new MobileLokmatSportsPage(driver);
		mobileHindiCricketNextPage = new MobileHindiCricketNextPage(driver);
		mobileHindiSectionPage = new MobileHindiSectionPage(driver);
		mobileHindiVideoSectionPage = new MobileHindiVideoSectionPage(driver);
		mobilePunjabSectionPage = new MobilePunjabSectionPage(driver);
		mobilePunjabCricketNextPage = new MobilePunjabCricketNextPage(driver);
		mobilePunjabVideoSectionPage= new MobilePunjabVideoSectionPage(driver);
		mobileTeluguSectionPage =new MobileTeluguSectionPage(driver);
		mobileTeluguCricketNextPage =new MobileTeluguCricketNextPage(driver);
		mobileTeluguVideoSectionPage =new MobileTeluguVideoSectionPage(driver);
		mobileOdiaSectionPage = new MobileOdiaSectionPage(driver);
		mobileTamilSectionPage =new MobileTamilSectionPage(driver); 
		mobileTamilCricketNextPage =new MobileTamilCricketNextPage(driver);
		mobileTamilVideoSectionPage =new MobileTamilVideoSectionPage(driver);
		mobileAssamVideoSectionPage = new MobileAssamVideosSectionPage(driver);
		ampValidatorPage = new AMPValidatorPage(driver);
		homePageLinksValidation = new HomePageLinksValidation(driver);
		desktopMetaTagValidation = new MetaTagValidation(driver);
		gaComscoreValidation=new GAComscoreValidation(driver);
		desktopOutbrainValidation = new DesktopOutbrainValidation(driver);
		mobileOutbrainValidation = new MobileOutbrainValidation(driver);
		structuredSchemaValidation = new StructuredSchemaValidation(driver);
		verifySocialShareIcons = new VerifySocialShareIcons(driver);
		verifyLatestNewsUpdatedTime= new VerifyLatestNewsUpdatedTime(driver);
		ampPhotoArticleConsumptionPage=new AMPPhotoArticleConsumptionPage(driver);
		gaComscoreAMPValidation=new GAComscoreAMPValidation(driver);
		ampHindiLandingPage=new AMPHindiLandingPage(driver);
		desktopSanityLandingPage = new DesktopSanityLandingPage(driver);
		mobileSanityLandingPage = new MobileSanityLandingPage(driver);
		ampSanityLandingPage = new AMPSanityLandingPage(driver);
		desktopHindiSanityLandingPage = new DesktopHindiSanityLandingPage(driver);
		mobileHindiSanityLandingPage = new MobileHindiSanityLandingPage(driver);
		ampHindiSanityLandingPage = new AMPHindiSanityLandingPage(driver);
		}
}